general {
    grab_focus = true
}

cache {
    enabled = true
}

finders {
    default_finder = desktop
    desktop_icons = true
    unicode_prefix = -
    math_prefix = =
    font_prefix = '
}

ui {
    # Dimensions (Largeur Hauteur)
    window_size = 650 350
}
