# Couleurs principales (Format Hyprland : 0xAARRGGBB)
background = 0xee14141e
base = 0xee282a36
alternate_base = 0xee1e1f29

# Typographie et texte
text = 0xfff8f8f2
bright_text = 0xffffffff
font_family = "Fira Code"
font_family_monospace = "Fira Code"
font_size = 12
small_font_size = 10
h1_size = 18
h2_size = 15
h3_size = 13

# Accents (Rose fluo et Violet)
accent = 0xffff007f
accent_secondary = 0xffbd93f9

# Arrondis
rounding_large = 12
rounding_small = 6

icon_theme = "breeze-dark"
