general {
    lock_cmd = pidof hyprlock || hyprlock       # Évite de lancer plusieurs instances
    before_sleep_cmd = loginctl lock-session    # Verrouille avant mise en veille
    after_sleep_cmd = hyprctl dispatch dpms on  # Rallume l'écran au réveil
    inhibit_sleep = 2                           # Mode auto : attend le verrouillage avant mise en veille
}

# 1. Baisse de la luminosité de l'écran (après 2 min 30)
listener {
    timeout = 150
    on-timeout = brightnessctl -s set 10        # Sauvegarde et réduit la luminosité
    on-resume = brightnessctl -r                # Restaure la luminosité à l'activité
}

# 2. Verrouillage de la session (après 5 min)
listener {
    timeout = 300
    on-timeout = loginctl lock-session          # Déclenche lock_cmd (hyprlock)
}

# 3. Extinction de l'écran via DPMS (après 5 min 30)
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off      # Éteint l'écran
    on-resume = hyprctl dispatch dpms on        # Rallume l'écran dès qu'on bouge la souris / touche le clavier
}

# 4. Mise en veille complète du système (après 30 min)
listener {
    timeout = 1800
    on-timeout = systemctl suspend              # Suspend la machine
}
